rootObjectAggregateName: Todo
properties:
  - title:
      type: lngKey
      key: todo.title
    key: title
    dataIndex: title
    valueType: string
    width: m
    formItemProps:
      rules:
        - required: true
          message: Please enter a Title
  - title:
      type: lngKey
      key: todo.description
    key: description
    dataIndex: description
    valueType: textarea
    width: m
    formItemProps: [ ]