title:
  type: lngKey
  key: pageTitle.todo
url: "/listdata/Todo"
avatar: "/icons/seminars.png"
pageType: ListData
projectionName: todo
editForm:
  $ref: editForm.yaml
createForm:
  $ref: createForm.yaml
itemActions:
  edit:
    type: form
    key: editForm
    title:
      type: lngKey
      key: action.edit
  delete:
    type: form
    key: deleteForm
    title:
      type: lngKey
      key: action.delete